### ISSUE TITLE
GSM

### ISSUE THREAD

**Issue by PetPolarBear** [stetro/ngn-sniffer#2]

**Comment by stetro** [comment]
We're getting the following information:
- Current Network (CDMA, EDGE, GSM, LTE ...)
- Current Signal Strength (defined in the GSM standard `TS 27.007`, section **8.5** )
  
  ```
  0        -113 dBm or less  
  1        -111 dBm  
  2...30   -109... -53 dBm  
  31        -51 dBm or greater  
  
  99 not known or not detectable
  ```
- IMEI/MEID, Network Country/Operator/OperatroName
- Sim Country/Operator/OperatorName/State/SerialNumber , Roaming Status, 
- Call State (Idle ect.), Data Activity, Line 1 Number
